spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: api-service
    server: ${API_ENDPOINT:http://localhost:8080}
    title: API Service
    version: 1.0.0
