spring:
  config:
    activate:
      on-profile: staging
  devtools:
    add-properties: true

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
openapi:
  service:
    api-docs: api-service
    server: ${API_ENDPOINT}
    title: API Service
    version: 1.0.0
